<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\District;

class DistrictSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $districts = [
            ['district_name' => 'ANANTAPUR','state_id' => '2'],
['district_name' => 'WEST GODAVARI','state_id' => '2'],
['district_name' => 'BANKA','state_id' => '5'],
['district_name' => 'BHAGALPUR','state_id' => '5'],
['district_name' => 'MADHEPURA','state_id' => '5'],
['district_name' => 'VISAKHAPATANAM','state_id' => '2'],
['district_name' => 'NIZAMABAD', 'state_id' => '31'],
['district_name' => 'KAMAREDDY', 'state_id' => '31'],
['district_name' => 'BARMER', 'state_id' => '28'],
['district_name' => 'JODHPUR', 'state_id' => '28'],
['district_name' => 'Y.S.R.','state_id' => '2'],
['district_name' => 'PATIALA', 'state_id' => '27'],
['district_name' => 'HAILAKANDI','state_id' => '4'],
['district_name' => 'KANPUR NAGAR', 'state_id' => '34'],
['district_name' => 'GORAKHPUR', 'state_id' => '34'],
['district_name' => 'PEDDAPALLI', 'state_id' => '31'],
['district_name' => 'KARIMNAGAR', 'state_id' => '31'],
['district_name' => 'SPSR NELLORE','state_id' => '2'],
['district_name' => 'MEDCHAL MALKAJGIRI', 'state_id' => '31'],
['district_name' => 'VIKARABAD', 'state_id' => '31'],
['district_name' => 'RANGA REDDY', 'state_id' => '31'],
['district_name' => 'GUNTUR','state_id' => '2'],
['district_name' => 'MOGA', 'state_id' => '27'],
['district_name' => 'BEGUSARAI','state_id' => '5'],
['district_name' => 'SANGAREDDY', 'state_id' => '31'],
['district_name' => 'MUNGER','state_id' => '5'],
['district_name' => 'BIDAR', 'state_id' => '15'],
['district_name' => 'FARIDKOT', 'state_id' => '27'],
['district_name' => 'KHAMMAM', 'state_id' => '31'],
['district_name' => 'SUPAUL','state_id' => '5'],
['district_name' => 'SIDDIPET', 'state_id' => '31'],
['district_name' => 'Niwari', 'state_id' => '19'],
['district_name' => 'KHAGARIA','state_id' => '5'],
['district_name' => 'SOUTH SALMARA MANCACHAR','state_id' => ' 4'],
['district_name' => 'BOKARO', 'state_id' => '14'],
['district_name' => 'CUTTACK', 'state_id' => '25'],
['district_name' => 'WARANGAL URBAN', 'state_id' => '31'],
['district_name' => 'LUDHIANA', 'state_id' => '27'],
['district_name' => 'CHATRA', 'state_id' => '14'],
['district_name' => 'RAMGARH', 'state_id' => '14'],
['district_name' => 'AURANGABAD','state_id' => '5'],
['district_name' => 'BHOJPUR','state_id' => '5'],
['district_name' => 'PRAKASAM','state_id' => '2'],
['district_name' => 'PALAMU', 'state_id' => '14'],
['district_name' => 'AMRAVATI', 'state_id' => '20'],
['district_name' => 'KARIMGANJ','state_id' => '4'],
['district_name' => 'EAST GODAVARI','state_id' => '2'],
['district_name' => 'HAZARIBAGH', 'state_id' => '14'],
['district_name' => 'ROHTAS','state_id' => '5'],
['district_name' => 'BARGARH', 'state_id' => '25'],
['district_name' => 'JHUNJHUNU', 'state_id' => '28'],
['district_name' => 'MADHUBANI','state_id' => '5'],
['district_name' => 'DHENKANAL', 'state_id' => '25'],
['district_name' => 'GHAZIABAD', 'state_id' => '34'],
['district_name' => 'DAKSHINA KANNADA', 'state_id' => '15'],
['district_name' => 'SAMASTIPUR','state_id' => '5'],
['district_name' => 'AGRA', 'state_id' => '34'],
['district_name' => 'BAKSA','state_id' => '4'],
['district_name' => 'BARPETA','state_id' => '4'],
['district_name' => 'NALBARI','state_id' => '4'],
['district_name' => 'CACHAR','state_id' => '4'],
['district_name' => 'SABAR KANTHA', 'state_id' => '10'],
['district_name' => 'JALORE', 'state_id' => '28'],
['district_name' => 'AHMADABAD', 'state_id' => '10'],
['district_name' => 'DARBHANGA','state_id' => '5'],
['district_name' => 'MAHESANA', 'state_id' => '10'],
['district_name' => 'KONDAGAON','state_id' => '7'],
['district_name' => 'MANCHERIAL', 'state_id' => '31'],
['district_name' => 'KUMURAM BHEEM ASIFABAD', 'state_id' => '31'],
['district_name' => 'WARANGAL RURAL', 'state_id' => '31'],
['district_name' => 'MAHABUBABAD', 'state_id' => '31'],
['district_name' => 'BILASPUR','state_id' => '7'],
['district_name' => 'Biswanath','state_id' => '4'],
['district_name' => 'SONITPUR','state_id' => '4'],
['district_name' => 'BASTAR','state_id' => '7'],
['district_name' => 'DANTEWADA','state_id' => ' 7'],
['district_name' => 'ANUGUL', 'state_id' => '25'],
['district_name' => 'GARHWA', 'state_id' => '14'],
['district_name' => 'JAJAPUR', 'state_id' => '25'],
['district_name' => 'S.A.S Nagar', 'state_id' => '27'],
['district_name' => 'TIRUCHIRAPPALLI', 'state_id' => '30'],
['district_name' => 'Jagitial', 'state_id' => '31'],
['district_name' => 'KENDRAPARA', 'state_id' => '25'],
['district_name' => 'VIZIANAGARAM','state_id' => ' 2'],
['district_name' => 'HANUMANGARH', 'state_id' => '28'],
['district_name' => 'JANJGIR-CHAMPA','state_id' => ' 7'],
['district_name' => 'MUNGELI','state_id' => ' 7'],
['district_name' => 'CHITTOOR','state_id' => ' 2'],
['district_name' => 'AJMER', 'state_id' => '28'],
['district_name' => 'NADIA', 'state_id' => '36'],
['district_name' => 'DIBRUGARH','state_id' => ' 4'],
['district_name' => 'PURBI CHAMPARAN','state_id' => ' 5'],
['district_name' => 'HYDERABAD', 'state_id' => '31'],
['district_name' => 'SARAN','state_id' => ' 5'],
['district_name' => 'LAKHIMPUR','state_id' => ' 4'],
['district_name' => 'KANKER','state_id' => ' 7'],
['district_name' => 'Nirmal', 'state_id' => '31'],
['district_name' => 'SUKMA','state_id' => ' 7'],
['district_name' => 'RAJNANDGAON','state_id' => ' 7'],
['district_name' =>  'PANNA', 'state_id' => '19'],
['district_name' =>  'PRAYAGRAJ', 'state_id' => '34'],
['district_name' =>  'PURNIA','state_id' => ' 5'],
['district_name' =>  'BIJAPUR','state_id' => ' 7'],
['district_name' =>  'YADADRI BHUVANAGIRI', 'state_id' => '31'],
['district_name' =>  'MEDAK', 'state_id' => '31'],
['district_name' =>  'SAHARSA','state_id' => ' 5'],
['district_name' =>  'SRIKAKULAM','state_id' => ' 2'],
['district_name' =>  'KURNOOL','state_id' => ' 2'],
['district_name' =>  'NALGONDA', 'state_id' => '31'],
['district_name' =>  'DHAMTARI','state_id' => ' 7'],
['district_name' =>  'CHIRANG','state_id' => ' 4'],
['district_name' =>  'BHADRAK', 'state_id' => '25'],
['district_name' =>  'BANAS KANTHA', 'state_id' => '10'],
['district_name' =>  'JAMTARA', 'state_id' => '14'],
['district_name' =>  'JANGOAN', 'state_id' => '31'],
['district_name' =>  'MAHABUBNAGAR', 'state_id' => '31'],
['district_name' =>  'Narayanpet', 'state_id' => '31'],
['district_name' =>  'SURYAPET', 'state_id' => '31'],
['district_name' =>  'JAYASHANKAR BHUPALAPALLY', 'state_id' => '31'],
['district_name' =>  'SITAMARHI','state_id' => ' 5'],
['district_name' =>  'PASHCHIM CHAMPARAN','state_id' => ' 5'],
['district_name' =>  'GAYA','state_id' => ' 5'],
['district_name' =>  'JHARSUGUDA', 'state_id' => '25'],
['district_name' =>  'GODDA', 'state_id' => '14'],
['district_name' =>  'DHUBRI','state_id' => ' 4'],
['district_name' =>  'Mulugu', 'state_id' => '31'],
['district_name' =>  'GANDHINAGAR', 'state_id' => '10'],
['district_name' =>  'MAJULI','state_id' => ' 4'],
['district_name' =>  'PURI', 'state_id' => '25'],
['district_name' =>  'LUCKNOW', 'state_id' => '34'],
['district_name' =>  'JOGULAMBA GADWAL', 'state_id' => '31'],
['district_name' =>  'DEOGHAR', 'state_id' => '14'],
['district_name' =>  'LATEHAR', 'state_id' => '14'],
['district_name' =>  'PATNA','state_id' => ' 5'],
['district_name' =>  'GOPALGANJ','state_id' => ' 5'],
['district_name' =>  'DUMKA', 'state_id' => '14'],
['district_name' =>  'NARAYANPUR','state_id' => ' 7'],
['district_name' =>  'MUZAFFARPUR','state_id' => ' 5'],
['district_name' =>  'KAPURTHALA', 'state_id' => '27'],
['district_name' =>  'GOALPARA','state_id' => ' 4'],
['district_name' =>  'ADILABAD', 'state_id' => '31'],
['district_name' =>  'SEONI', 'state_id' => '19'],
['district_name' =>  'KRISHNA','state_id' => ' 2'],
['district_name' =>  'VILLUPURAM', 'state_id' => '30'],
['district_name' =>  'ALIGARH', 'state_id' => '34'],
['district_name' =>  'KATIHAR','state_id' => ' 5'],
['district_name' =>  'RAJANNA SIRCILLA', 'state_id' => '31'],
['district_name' =>  'PAKUR', 'state_id' => '14'],
['district_name' =>  'JHANSI', 'state_id' => '34'],
['district_name' =>  'JAMUI','state_id' => ' 5'],
['district_name' =>  'ARWAL','state_id' => ' 5'],
['district_name' =>  'DHARMAPURI', 'state_id' => '30'],
['district_name' =>  'JEHANABAD','state_id' => ' 5'],
['district_name' =>  'SIWAN','state_id' => ' 5'],
['district_name' =>  'KHORDHA', 'state_id' => '25'],
['district_name' =>  'SUNDARGARH', 'state_id' => '25'],
['district_name' =>  'KENDUJHAR', 'state_id' => '25'],
['district_name' =>  'WANAPARTHY', 'state_id' => '31'],
['district_name' =>  'PATAN', 'state_id' => '10'],
['district_name' =>  'JAGATSINGHAPUR', 'state_id' => '25'],
['district_name' =>  'DHEMAJI','state_id' => ' 4'],
['district_name' =>  'NARMADA', 'state_id' => '10'],
['district_name' =>  'NAGARKURNOOL', 'state_id' => '31'],
['district_name' =>  'SAHEBGANJ', 'state_id' => '14'],
['district_name' =>  'DURG','state_id' => ' 7'],
['district_name' =>  'BHARUCH', 'state_id' => '10'],
['district_name' =>  'KAMRUP','state_id' => ' 4'],
['district_name' =>  'HASSAN', 'state_id' => '15'],
['district_name' =>  'KABIRDHAM','state_id' => ' 7'],
['district_name' =>  'KOKRAJHAR','state_id' => ' 4'],
['district_name' =>  'KAMRUP METRO','state_id' => ' 4'],
['district_name' =>  'KANGRA', 'state_id' => '12'],
['district_name' =>  'KISHANGANJ','state_id' => ' 5'],
['district_name' =>  'DAVANGERE', 'state_id' => '15'],
['district_name' =>  'BALODA BAZAR','state_id' => ' 7'],
['district_name' =>  'MAHASAMUND','state_id' => ' 7'],
['district_name' =>  'RAIPUR','state_id' => ' 7'],
['district_name' =>  'VADODARA', 'state_id' => '10'],
['district_name' =>  'ANAND', 'state_id' => '10'],
['district_name' =>  'KHEDA', 'state_id' => '10'],
['district_name' =>  'GARIYABAND','state_id' => ' 7'],
['district_name' =>  'NAGAON','state_id' => ' 4'],
['district_name' =>  'NAVSARI', 'state_id' => '10'],
['district_name' =>  'BHADRADRI KOTHAGUDEM', 'state_id' => '31'],
['district_name' =>  'LAKHISARAI','state_id' => ' 5'],
['district_name' =>  'PRATAPGARH', 'state_id' => '28'],
['district_name' =>  'JIND', 'state_id' => '11'],
['district_name' =>  'KORBA','state_id' => ' 7'],
['district_name' =>  'KOTA', 'state_id' => '28'],
['district_name' =>  'SAHARANPUR', 'state_id' => '34'],
['district_name' =>  'THRISSUR', 'state_id' => '16'],
['district_name' =>  'BEMETARA','state_id' => '7'],
['district_name' =>  'RAIGARH','state_id' => '7'],
['district_name' =>  'KANNUR', 'state_id' => '16'],
['district_name' =>  'BARAN', 'state_id' => '28'],
['district_name' =>  'AMRELI', 'state_id' => '10'],
['district_name' =>  'GOLAGHAT','state_id' => '4'],
['district_name' =>  'BALOD','state_id' => '7'],
['district_name' =>  'BHAVNAGAR', 'state_id' => '10'],
['district_name' =>  'RAJKOT', 'state_id' => '10'],
['district_name' =>  'WEST KARBI ANGLONG','state_id' => '4'],
['district_name' =>  'MORBI', 'state_id' => '10'],
['district_name' =>  'BOTAD', 'state_id' => '10'],
['district_name' =>  'JORHAT','state_id' => '4'],
['district_name' =>  'TINSUKIA','state_id' => '4'],
['district_name' =>  'MEERUT', 'state_id' => '34'],
['district_name' =>  'PALWAL', 'state_id' => '11'],
['district_name' =>  'ERNAKULAM', 'state_id' => '16'],
['district_name' =>  'RAISEN', 'state_id' => '19'],
['district_name' =>  'ARVALLI', 'state_id' => '10'],
['district_name' =>  'KAIMUR (BHABUA)','state_id' => '5'],
['district_name' =>  'NALANDA','state_id' => '5'],
['district_name' =>  'KALABURAGI', 'state_id' => '15'],
['district_name' =>  'KARBI ANGLONG','state_id' => '4'],
['district_name' =>  'SHEIKHPURA','state_id' => '5'],
['district_name' =>  'VARANASI', 'state_id' => '34'],
['district_name' =>  'HOJAI','state_id' => '4'],
['district_name' =>  'CHENGALPATTU', 'state_id' => '30'],
['district_name' =>  'MORADABAD', 'state_id' => '34'],
['district_name' =>  'SURENDRANAGAR', 'state_id' => '10'],
['district_name' =>  'KODERMA', 'state_id' => '14'],
['district_name' =>  'BONGAIGAON','state_id' => '4'],
['district_name' =>  'DHANBAD', 'state_id' => '14'],
['district_name' =>  'BAREILLY', 'state_id' => '34'],
['district_name' =>  'SOUTH','state_id' => '8'],
['district_name' =>  'JUNAGADH', 'state_id' => '10'],
['district_name' =>  'MUZAFFARNAGAR', 'state_id' => '34'],
['district_name' =>  'GIR SOMNATH', 'state_id' => '10'],
['district_name' =>  'SOUTH WEST','state_id' => '8'],
['district_name' =>  'WEST','state_id' => '8'],
['district_name' =>  'UDAIPUR', 'state_id' => '28'],
['district_name' =>  'ANANTNAG', 'state_id' => '13'],
['district_name' =>  'PORBANDAR', 'state_id' => '10'],
['district_name' =>  'POONCH', 'state_id' => '13'],
['district_name' =>  'RAJOURI', 'state_id' => '13'],
['district_name' =>  'VAISHALI','state_id' => '5'],
['district_name' =>  'RI BHOI', 'state_id' => '22'],
['district_name' =>  'KODAGU', 'state_id' => '15'],
['district_name' =>  'Gaurella Pendra Marwahi','state_id' => '7'],
['district_name' =>  'RANCHI', 'state_id' => '14'],
['district_name' =>  'KHUNTI', 'state_id' => '14'],
['district_name' =>  'CHIKKAMAGALURU', 'state_id' => '15'],
['district_name' =>  'CHITRADURGA', 'state_id' => '15'],
['district_name' =>  'UDALGURI','state_id' => '4'],
['district_name' =>  'DARRANG','state_id' => '4'],
['district_name' =>  'CHARAIDEO','state_id' => '4'],
['district_name' =>  'SURGUJA','state_id' => '7'],
['district_name' =>  'SIVASAGAR','state_id' => '4'],
['district_name' =>  'MARIGAON','state_id' => '4'],
['district_name' =>  'SHEOHAR','state_id' => '5'],
['district_name' =>  'DIMA HASAO','state_id' => ' 4'],
['district_name' =>  'SURAJPUR','state_id' => '7'],
['district_name' =>  'CHHOTAUDEPUR', 'state_id' => '10'],
['district_name' =>  'PANCHKULA', 'state_id' => '11'],
['district_name' =>  'SHOPIAN', 'state_id' => '13'],
['district_name' =>  'DEVBHUMI DWARKA', 'state_id' => '10'],
['district_name' =>  'NAWADA','state_id' => '5'],
['district_name' =>  'AMBALA', 'state_id' => '11'],
['district_name' =>  'JAMNAGAR', 'state_id' => '10'],
['district_name' =>  'ARARIA','state_id' => '5'],
['district_name' =>  'GIRIDIH', 'state_id' => '14'],
['district_name' =>  'SURAT', 'state_id' => '10'],
['district_name' =>  'HAMIRPUR', 'state_id' => '12'],
['district_name' =>  'PANCH MAHALS', 'state_id' => '10'],
['district_name' =>  'IMPHAL EAST', 'state_id' => '21'],
['district_name' =>  'IMPHAL WEST', 'state_id' => '21'],
['district_name' =>  'SENAPATI', 'state_id' => '21'],
['district_name' =>  'TAMENGLONG', 'state_id' => '21'],
['district_name' =>  'REWARI', 'state_id' => '11'],
['district_name' =>  'JIRIBAM', 'state_id' => '21'],
['district_name' =>  'CHURACHANDPUR', 'state_id' => '21'],
['district_name' =>  'KAKCHING', 'state_id' => '21'],
['district_name' =>  'TENGNOUPAL', 'state_id' => '21'],
['district_name' =>  'PHERZAWL', 'state_id' => '21'],
['district_name' =>  'NONEY', 'state_id' => '21'],
['district_name' =>  'CHANDEL', 'state_id' => '21'],
['district_name' =>  'KANGPOKPI', 'state_id' => '21'],
['district_name' =>  'BUXAR','state_id' => '5'],
['district_name' =>  'Mahisagar', 'state_id' => '10'],
['district_name' =>  'UKHRUL', 'state_id' => '21'],
['district_name' =>  'ALAPPUZHA', 'state_id' => '16'],
['district_name' =>  'KACHCHH', 'state_id' => '10'],
['district_name' =>  'VALSAD', 'state_id' => '10'],
['district_name' =>  'MAHENDRAGARH', 'state_id' => '11'],
['district_name' =>  'MYSURU', 'state_id' => '15'],
['district_name' =>  'BELAGAVI', 'state_id' => '15'],
['district_name' =>  'CHAMARAJANAGARA', 'state_id' => '15'],
['district_name' =>  'BALRAMPUR','state_id' => '7'],
['district_name' =>  'KOREA','state_id' => '7'],
['district_name' =>  'IDUKKI', 'state_id' => '16'],
['district_name' =>  'RAMANAGARA', 'state_id' => '15'],
['district_name' =>  'BENGALURU URBAN', 'state_id' => '15'],
['district_name' =>  'BENGALURU RURAL', 'state_id' => '15'],
['district_name' =>  'ROHTAK', 'state_id' => '11'],
['district_name' =>  'REASI', 'state_id' => '13'],
['district_name' =>  'DODA', 'state_id' => '13'],
['district_name' =>  'KISHTWAR', 'state_id' => '13'],
['district_name' =>  'UDHAMPUR', 'state_id' => '13'],
['district_name' =>  'HISAR', 'state_id' => '11'],
['district_name' =>  'SONIPAT', 'state_id' => '11'],
['district_name' =>  'RAMBAN', 'state_id' => '13'],
['district_name' =>  'FATEHABAD', 'state_id' => '11'],
['district_name' =>  'LAHUL AND SPITI', 'state_id' => '12'],
['district_name' =>  'MANDI', 'state_id' => '12'],
['district_name' =>  'WEST SINGHBHUM', 'state_id' => '14'],
['district_name' =>  'JHAJJAR', 'state_id' => '11'],
['district_name' =>  'KULLU', 'state_id' => '12'],
['district_name' =>  'GUMLA', 'state_id' => '14'],
['district_name' =>  'TAPI', 'state_id' => '10'],
['district_name' =>  'DANG', 'state_id' => '10'],
['district_name' =>  'UNA', 'state_id' => '12'],
['district_name' =>  'DIU', 'state_id' => '32'],
['district_name' =>  'JASHPUR','state_id' => ' 7'],
['district_name' =>  'DOHAD', 'state_id' => '10'],
['district_name' =>  'KAITHAL', 'state_id' => '11'],
['district_name' =>  'LOHARDAGA', 'state_id' => '14'],
['district_name' =>  'KURUKSHETRA', 'state_id' => '11'],
['district_name' =>  'WAYANAD', 'state_id' => '16'],
['district_name' =>  'GADAG', 'state_id' => '15'],
['district_name' =>  'NORTH EAST','state_id' => '8'],
['district_name' =>  'KULGAM', 'state_id' => '13'],
['district_name' =>  'PULWAMA', 'state_id' => '13'],
['district_name' =>  'BALLARI', 'state_id' => '15'],
['district_name' =>  'KARNAL', 'state_id' => '11'],
['district_name' =>  'SIRSA', 'state_id' => '11'],
['district_name' =>  'PANIPAT', 'state_id' => '11'],
['district_name' =>  'DHARWAD', 'state_id' => '15'],
['district_name' =>  'MALAPPURAM', 'state_id' => '16'],
['district_name' =>  'KOZHIKODE', 'state_id' => '16'],
['district_name' =>  'CHANDRAPUR', 'state_id' => '20'],
['district_name' =>  'BAGALKOTE', 'state_id' => '15'],
['district_name' =>  'BARAMULLA', 'state_id' => '13'],
['district_name' =>  'SHIMLA', 'state_id' => '12'],
['district_name' =>  'GURUGRAM', 'state_id' => '11'],
['district_name' =>  'YADGIR', 'state_id' => '15'],
['district_name' =>  'BALESHWAR', 'state_id' => '25'],
['district_name' =>  'OSMANABAD', 'state_id' => '20'],
['district_name' =>  'SATARA', 'state_id' => '20'],
['district_name' =>  'SAITUAL', 'state_id' => '23'],
['district_name' =>  'SERCHHIP', 'state_id' => '23'],
['district_name' =>  'DHAR', 'state_id' => '19'],
['district_name' =>  'SAMBA', 'state_id' => '13'],
['district_name' =>  'JAMMU', 'state_id' => '13'],
['district_name' =>  'BANDIPORA', 'state_id' => '13'],
['district_name' =>  'KUPWARA', 'state_id' => '13'],
['district_name' =>  'GANDERBAL', 'state_id' => '13'],
['district_name' =>  'NUH', 'state_id' => '11'],
['district_name' =>  'JALANDHAR', 'state_id' => '27'],
['district_name' =>  'NORTH','state_id' => '8'],
['district_name' =>  'NORTH WEST','state_id' => '8'],
['district_name' =>  'GADCHIROLI', 'state_id' => '20'],
['district_name' =>  'NAYAGARH', 'state_id' => '25'],
['district_name' =>  'LATUR', 'state_id' => '20'],
['district_name' =>  'NUAPADA', 'state_id' => '25'],
['district_name' =>  'KALAHANDI', 'state_id' => '25'],
['district_name' =>  'GAJAPATI', 'state_id' => '25'],
['district_name' =>  'NEW DELHI','state_id' => ' 8'],
['district_name' =>  'SRINAGAR', 'state_id' => '13'],
['district_name' =>  'EAST KHASI HILLS', 'state_id' => '22'],
['district_name' =>  'WEST JAINTIA HILLS', 'state_id' => '22'],
['district_name' =>  'EAST JAINTIA HILLS', 'state_id' => '22'],
['district_name' =>  'SOUTH WEST KHASI HILLS', 'state_id' => '22'],
['district_name' =>  'WEST KHASI HILLS', 'state_id' => '22'],
['district_name' =>  'AKOLA', 'state_id' => '20'],
['district_name' =>  'NAGPUR', 'state_id' => '20'],
['district_name' =>  'DADRA AND NAGAR HAVELI', 'state_id' => '32'],
['district_name' =>  'Shahid Bhagat Singh Nagar', 'state_id' => '27'],
['district_name' =>  'EAST','state_id' => '8'],
['district_name' =>  'FARIDABAD', 'state_id' => '11'],
['district_name' =>  'KHARGONE', 'state_id' => '19'],
['district_name' =>  'NANDURBAR', 'state_id' => '20'],
['district_name' =>  'KATHUA', 'state_id' => '13'],
['district_name' =>  'CENTRAL','state_id' => '8'],
['district_name' =>  'JAISALMER', 'state_id' => '28'],
['district_name' =>  'SIRMAUR', 'state_id' => '12'],
['district_name' =>  'DAMAN', 'state_id' => '32'],
['district_name' =>  'SHIVAMOGGA', 'state_id' => '15'],
['district_name' =>  'MAYURBHANJ', 'state_id' => '25'],
['district_name' =>  'DHULE', 'state_id' => '20'],
['district_name' =>  'SHAHDARA','state_id' => ' 8'],
['district_name' =>  'AMRITSAR', 'state_id' => '27'],
['district_name' =>  'VIJAYAPURA', 'state_id' => '15'],
['district_name' =>  'BATHINDA', 'state_id' => '27'],
['district_name' =>  'LEH LADAKH', 'state_id' => '17'],
['district_name' =>  'KARGIL', 'state_id' => '17'],
['district_name' =>  'THOUBAL', 'state_id' => '21'],
['district_name' =>  'SOLAN', 'state_id' => '12'],
['district_name' =>  'JALGAON', 'state_id' => '20'],
['district_name' =>  'SOUTH WEST GARO HILLS', 'state_id' => '22'],
['district_name' =>  'SOUTH GARO HILLS', 'state_id' => '22'],
['district_name' =>  'YAVATMAL', 'state_id' => '20'],
['district_name' =>  'JABALPUR', 'state_id' => '19'],
['district_name' =>  'SANGRUR', 'state_id' => '27'],
['district_name' =>  'SEHORE', 'state_id' => '19'],
['district_name' =>  'KINNAUR', 'state_id' => '12'],
['district_name' =>  'WEST GARO HILLS', 'state_id' => '22'],
['district_name' =>  'BARNALA', 'state_id' => '27'],
['district_name' =>  'NASHIK', 'state_id' => '20'],
['district_name' =>  'KOLASIB', 'state_id' => '23'],
['district_name' =>  'AIZAWL', 'state_id' => '23'],
['district_name' =>  'LUNGLEI', 'state_id' => '23'],
['district_name' =>  'MAMIT', 'state_id' => '23'],
['district_name' =>  'BALLIA', 'state_id' => '34'],
['district_name' =>  'WASHIM', 'state_id' => '20'],
['district_name' =>  'SHAJAPUR', 'state_id' => '19'],
['district_name' =>  'DIMAPUR', 'state_id' => '24'],
['district_name' =>  'MOKOKCHUNG', 'state_id' => '24'],
['district_name' =>  'ZUNHEBOTO', 'state_id' => '24'],
['district_name' =>  'KOHIMA', 'state_id' => '24'],
['district_name' =>  'MON', 'state_id' => '24'],
['district_name' =>  'PHEK', 'state_id' => '24'],
['district_name' =>  'AGAR MALWA', 'state_id' => '19'],
['district_name' =>  'CHAMBA', 'state_id' => '12'],
['district_name' =>  'NORTH GARO HILLS', 'state_id' => '22'],
['district_name' =>  'EAST GARO HILLS', 'state_id' => '22'],
['district_name' =>  'SIMDEGA', 'state_id' => '14'],
['district_name' =>  'KOPPAL', 'state_id' => '15'],
['district_name' =>  'SONEPUR', 'state_id' => '25'],
['district_name' =>  'MALERKOTLA', 'state_id' => '27'],
['district_name' =>  'South Tripura', 'state_id' => '33'],
['district_name' =>  'Sepahijala', 'state_id' => '33'],
['district_name' =>  'AHMEDNAGAR', 'state_id' => '20'],
['district_name' =>  'BALANGIR', 'state_id' => '25'],
['district_name' =>  'KOTTAYAM', 'state_id' => '16'],
['district_name' =>  'HINGOLI', 'state_id' => '20'],
['district_name' =>  'JALNA', 'state_id' => '20'],
['district_name' =>  'WEST SIANG','state_id' => '3'],
['district_name' =>  'LOWER SUBANSIRI','state_id' => '3'],
['district_name' =>  'RATNAGIRI', 'state_id' => '20'],
['district_name' =>  'SARAIKELA KHARSAWAN', 'state_id' => '14'],
['district_name' =>  'Gomati', 'state_id' => '33'],
['district_name' =>  'PAPUM PARE','state_id' => '3'],
['district_name' =>  'HOSHIARPUR', 'state_id' => '27'],
['district_name' =>  'JAIPUR', 'state_id' => '28'],
['district_name' =>  'BULDHANA', 'state_id' => '20'],
['district_name' =>  'UDUPI', 'state_id' => '15'],
['district_name' =>  'LONGLENG', 'state_id' => '24'],
['district_name' =>  'Budgam', 'state_id' => '13'],
['district_name' =>  'EAST SINGHBUM', 'state_id' => '14'],
['district_name' =>  'Hnahthial', 'state_id' => '23'],
['district_name' =>  'TUENSANG', 'state_id' => '24'],
['district_name' =>  'PATHANAMTHITTA', 'state_id' => '16'],
['district_name' =>  'CHANGLANG','state_id' => '3'],
['district_name' =>  'SIANG','state_id' => '3'],
['district_name' =>  'SHI YOMI','state_id' => '3'],
['district_name' =>  'DINDORI', 'state_id' => '19'],
['district_name' =>  'BIKANER', 'state_id' => '28'],
['district_name' =>  'MANDLA', 'state_id' => '19'],
['district_name' =>  'TIKAMGARH', 'state_id' => '19'],
['district_name' =>  'MATHURA', 'state_id' => '34'],
['district_name' =>  'HATHRAS', 'state_id' => '34'],
['district_name' =>  'KOLLAM', 'state_id' => '16'],
['district_name' =>  'CHAMPHAI', 'state_id' => '23'],
['district_name' =>  'YAMUNANAGAR', 'state_id' => '11'],
['district_name' =>  'THIRUVANANTHAPURAM', 'state_id' => '16'],
['district_name' =>  'SHAHJAHANPUR', 'state_id' => '34'],
['district_name' =>  'KAMJONG', 'state_id' => '21'],
['district_name' =>  'KAUSHAMBI', 'state_id' => '34'],
['district_name' =>  'CHANDAULI', 'state_id' => '34'],
['district_name' =>  'PILIBHIT', 'state_id' => '34'],
['district_name' =>  'TIRUNELVELI', 'state_id' => '30'],
['district_name' =>  'CHARKI DADRI', 'state_id' => '11'],
['district_name' =>  'ERODE', 'state_id' => '30'],
['district_name' =>  'BHIWANI', 'state_id' => '11'],
['district_name' =>  'LAKSHADWEEP DISTRICT', 'state_id' => '18'],
['district_name' =>  'Tirupathur', 'state_id' => '30'],
['district_name' =>  'SIVAGANGA', 'state_id' => '30'],
['district_name' =>  'TUTICORIN', 'state_id' => '30'],
['district_name' =>  'TIRUPPUR', 'state_id' => '30'],
['district_name' =>  'MANDYA', 'state_id' => '15'],
['district_name' =>  'UTTARA KANNADA', 'state_id' => '15'],
['district_name' =>  'AMROHA', 'state_id' => '34'],
['district_name' =>  'Tarn Taran', 'state_id' => '27'],
['district_name' =>  'KOLAR', 'state_id' => '15'],
['district_name' =>  'SINDHUDURG', 'state_id' => '20'],
['district_name' =>  'MAHE', 'state_id' => '26'],
['district_name' =>  'BASTI', 'state_id' => '34'],
['district_name' =>  'SANT KABEER NAGAR', 'state_id' => '34'],
['district_name' =>  'KANDHAMAL', 'state_id' => '25'],
['district_name' =>  'COIMBATORE', 'state_id' => '30'],
['district_name' =>  'PALAKKAD', 'state_id' => '16'],
['district_name' =>  'LAWNGTLAI', 'state_id' => '23'],
['district_name' =>  'FARRUKHABAD', 'state_id' => '34'],
['district_name' =>  'TUMAKURU', 'state_id' => '15'],
['district_name' =>  'BOUDH', 'state_id' => '25'],
['district_name' =>  'SIDDHARTH NAGAR', 'state_id' => '34'],
['district_name' =>  'CHANDIGARH','state_id' => ' 6'],
['district_name' =>  'RAICHUR', 'state_id' => '15'],
['district_name' =>  'HAVERI', 'state_id' => '15'],
['district_name' =>  'CHIKKABALLAPURA', 'state_id' => '15'],
['district_name' =>  'KRISHNAGIRI', 'state_id' => '30'],
['district_name' =>  'NARSINGHPUR', 'state_id' => '19'],
['district_name' =>  'NANDED', 'state_id' => '20'],
['district_name' =>  'JHALAWAR', 'state_id' => '28'],
['district_name' =>  'THE NILGIRIS', 'state_id' => '30'],
['district_name' =>  'THIRUVALLUR', 'state_id' => '30'],
['district_name' =>  'LALITPUR', 'state_id' => '34'],
['district_name' =>  'CHHINDWARA', 'state_id' => '19'],
['district_name' =>  'ALWAR', 'state_id' => '28'],
['district_name' =>  'Dhalai', 'state_id' => '33'],
['district_name' =>  'MAHARAJGANJ', 'state_id' => '34'],
['district_name' =>  'North Tripura', 'state_id' => '33'],
['district_name' =>  'Khowai', 'state_id' => '33'],
['district_name' =>  'HOSHANGABAD', 'state_id' => '19'],
['district_name' =>  'Unakoti', 'state_id' => '33'],
['district_name' =>  'TENKASI', 'state_id' => '30'],
['district_name' =>  'DAMOH', 'state_id' => '19'],
['district_name' =>  'KANCHIPURAM', 'state_id' => '30'],
['district_name' =>  'VIDISHA', 'state_id' => '19'],
['district_name' =>  'REWA', 'state_id' => '19'],
['district_name' =>  'BALAGHAT', 'state_id' => '19'],
['district_name' =>  'SIDHI', 'state_id' => '19'],
['district_name' =>  'SATNA', 'state_id' => '19'],
['district_name' =>  'HAPUR', 'state_id' => '34'],
['district_name' =>  'BAGHPAT', 'state_id' => '34'],
['district_name' =>  'SINGRAULI', 'state_id' => '19'],
['district_name' =>  'KASARAGOD', 'state_id' => '16'],
['district_name' =>  'CHHATARPUR', 'state_id' => '19'],
['district_name' =>  'BHOPAL', 'state_id' => '19'],
['district_name' =>  'BUNDI', 'state_id' => '28'],
['district_name' =>  'NEEMUCH', 'state_id' => '19'],
['district_name' =>  'JHABUA', 'state_id' => '19'],
['district_name' =>  'ALIRAJPUR', 'state_id' => '19'],
['district_name' =>  'BARWANI', 'state_id' => '19'],
['district_name' =>  'BETUL', 'state_id' => '19'],
['district_name' =>  'BHIND', 'state_id' => '19'],
['district_name' =>  'GWALIOR', 'state_id' => '19'],
['district_name' =>  'SOUTH GOA','state_id' => '9'],
['district_name' =>  'NORTH GOA','state_id' => '9'],
['district_name' =>  'SHAHDOL', 'state_id' => '19'],
['district_name' =>  'TIRUVANNAMALAI', 'state_id' => '30'],
['district_name' =>  'GANJAM', 'state_id' => '25'],
['district_name' =>  'BURHANPUR', 'state_id' => '19'],
['district_name' =>  'SAGAR', 'state_id' => '19'],
['district_name' =>  'RAJGARH', 'state_id' => '19'],
['district_name' =>  'RATLAM', 'state_id' => '19'],
['district_name' =>  'DATIA', 'state_id' => '19'],
['district_name' =>  'VELLORE', 'state_id' => '30'],
['district_name' =>  'SHEOPUR', 'state_id' => '19'],
['district_name' =>  'MORENA', 'state_id' => '19'],
['district_name' =>  'BHARATPUR', 'state_id' => '28'],
['district_name' =>  'DUNGARPUR', 'state_id' => '28'],
['district_name' =>  'DHOLPUR', 'state_id' => '28'],
['district_name' =>  'SHIVPURI', 'state_id' => '19'],
['district_name' =>  'NAGAUR', 'state_id' => '28'],
['district_name' =>  'DEWAS', 'state_id' => '19'],
['district_name' =>  'DINDIGUL', 'state_id' => '30'],
['district_name' =>  'THIRUVARUR', 'state_id' => '30'],
['district_name' =>  'MANDSAUR', 'state_id' => '19'],
['district_name' =>  'EAST NIMAR', 'state_id' => '19'],
['district_name' =>  'SAMBALPUR', 'state_id' => '25'],
['district_name' =>  'DEOGARH', 'state_id' => '25'],
['district_name' =>  'SOLAPUR', 'state_id' => '20'],
['district_name' =>  'DAUSA', 'state_id' => '28'],
['district_name' =>  'BHANDARA', 'state_id' => '20'],
['district_name' =>  'KATNI', 'state_id' => '19'],
['district_name' =>  'SANGLI', 'state_id' => '20'],
['district_name' =>  'GUNA', 'state_id' => '19'],
['district_name' =>  'BANSWARA', 'state_id' => '28'],
['district_name' =>  'PUNE', 'state_id' => '20'],
['district_name' =>  'RAIGAD', 'state_id' => '20'],
['district_name' =>  'HARDA', 'state_id' => '19'],
['district_name' =>  'PARBHANI', 'state_id' => '20'],
['district_name' =>  'THANE', 'state_id' => '20'],
['district_name' =>  'MEDINIPUR WEST', 'state_id' => '36'],
['district_name' =>  'NAMAKKAL', 'state_id' => '30'],
['district_name' =>  'SALEM', 'state_id' => '30'],
['district_name' =>  'AYODHYA', 'state_id' => '34'],
['district_name' =>  'CHURU', 'state_id' => '28'],
['district_name' =>  'PALGHAR', 'state_id' => '20'],
['district_name' =>  'WARDHA', 'state_id' => '20'],
['district_name' =>  'MALKANGIRI', 'state_id' => '25'],
['district_name' =>  'MEDINIPUR EAST', 'state_id' => '36'],
['district_name' =>  'KOLHAPUR', 'state_id' => '20'],
['district_name' =>  'ANUPPUR', 'state_id' => '19'],
['district_name' =>  'UMARIA', 'state_id' => '19'],
['district_name' =>  'SRI MUKTSAR SAHIB', 'state_id' => '27'],
['district_name' =>  'AMBEDKAR NAGAR', 'state_id' => '34'],
['district_name' =>  'KORAPUT', 'state_id' => '25'],
['district_name' =>  'FATEHGARH SAHIB', 'state_id' => '27'],
['district_name' =>  'RAMANATHAPURAM', 'state_id' => '30'],
['district_name' =>  'MANSA', 'state_id' => '27'],
['district_name' =>  'CUDDALORE', 'state_id' => '30'],
['district_name' =>  'SIROHI', 'state_id' => '28'],
['district_name' =>  'MIRZAPUR', 'state_id' => '34'],
['district_name' =>  'KANNAUJ', 'state_id' => '34'],
['district_name' =>  'PONDICHERRY', 'state_id' => '26'],
['district_name' =>  'MUMBAI', 'state_id' => '20'],
['district_name' =>  'SONBHADRA', 'state_id' => '34'],
['district_name' =>  'RAJSAMAND', 'state_id' => '28'],
['district_name' =>  'ASHOKNAGAR', 'state_id' => '19'],
['district_name' =>  'SIKAR', 'state_id' => '28'],
['district_name' =>  'UJJAIN', 'state_id' => '19'],
['district_name' =>  'INDORE', 'state_id' => '19'],
['district_name' =>  'WOKHA', 'state_id' => '24'],
['district_name' =>  'KIPHIRE', 'state_id' => '24'],
['district_name' =>  'PEREN', 'state_id' => '24'],
['district_name' =>  'CHITTORGARH', 'state_id' => '28'],
['district_name' =>  'FATEHPUR', 'state_id' => '34'],
['district_name' =>  'MAU', 'state_id' => '34'],
['district_name' =>  'KALLAKURICHI', 'state_id' => '30'],
['district_name' =>  'BAHRAICH', 'state_id' => '34'],
['district_name' =>  'Ariyalur', 'state_id' => '30'],
['district_name' =>  'NAGAPATTINAM', 'state_id' => '30'],
['district_name' =>  'NABARANGPUR', 'state_id' => '25'],
['district_name' =>  'THANJAVUR', 'state_id' => '30'],
['district_name' =>  'BEED', 'state_id' => '20'],
['district_name' =>  'SAWAI MADHOPUR', 'state_id' => '28'],
['district_name' =>  'KARAULI', 'state_id' => '28'],
['district_name' =>  'JAUNPUR', 'state_id' => '34'],
['district_name' =>  'ETAH', 'state_id' => '34'],
['district_name' =>  'AZAMGARH', 'state_id' => '34'],
['district_name' =>  'GHAZIPUR', 'state_id' => '34'],
['district_name' =>  'TAWANG','state_id' => '3'],
['district_name' =>  'LOHIT','state_id' => '3'],
['district_name' =>  'EAST SIANG','state_id' => '3'],
['district_name' =>  'KURUNG KUMEY','state_id' => '3'],
['district_name' =>  'EAST KAMENG','state_id' => '3'],
['district_name' =>  'NAMSAI','state_id' => '3'],
['district_name' =>  'LOWER SIANG','state_id' => '3'],
['district_name' =>  'LOWER DIBANG VALLEY','state_id' => '3'],
['district_name' =>  'PUDUKKOTTAI', 'state_id' => '30'],
['district_name' =>  'West Tripura', 'state_id' => '33'],
['district_name' =>  'UPPER SIANG','state_id' => '3'],
['district_name' =>  'PAKKE KESSANG','state_id' => '3'],
['district_name' =>  'Noklak', 'state_id' => '24'],
['district_name' =>  'TONK', 'state_id' => '28'],
['district_name' =>  'WEST KAMENG','state_id' => '3'],
['district_name' =>  'BISHNUPUR', 'state_id' => '21'],
['district_name' =>  'RAYAGADA', 'state_id' => '25'],
['district_name' =>  'KARUR', 'state_id' => '30'],
['district_name' =>  'KRA DAADI','state_id' => '3'],
['district_name' =>  'KHAWZAWL', 'state_id' => '23'],
['district_name' =>  'DIBANG VALLEY','state_id' => '3'],
['district_name' =>  'LONGDING','state_id' => '3'],
['district_name' =>  'KANNIYAKUMARI', 'state_id' => '30'],
['district_name' =>  'FIROZEPUR', 'state_id' => '27'],
['district_name' =>  'FAZILKA', 'state_id' => '27'],
['district_name' =>  'GURDASPUR', 'state_id' => '27'],
['district_name' =>  'ETAWAH', 'state_id' => '34'],
['district_name' =>  'SAIHA', 'state_id' => '23'],
['district_name' =>  'UPPER SUBANSIRI','state_id' => '3'],
['district_name' =>  'BHILWARA', 'state_id' => '28'],
['district_name' =>  'TIRAP','state_id' => '3'],
['district_name' =>  'LEPARADA','state_id' => '3'],
['district_name' =>  'GAUTAM BUDDHA NAGAR', 'state_id' => '34'],
['district_name' =>  'ANJAW','state_id' => '3'],
['district_name' =>  'PALI', 'state_id' => '28'],
['district_name' =>  'GONDIA', 'state_id' => '20'],
['district_name' =>  'KAMLE','state_id' => '3'],
['district_name' =>  'Kasganj', 'state_id' => '34'],
['district_name' =>  'RUPNAGAR', 'state_id' => '27'],
['district_name' =>  'PATHANKOT', 'state_id' => '27'],
['district_name' =>  'FIROZABAD', 'state_id' => '34'],
['district_name' =>  'VIRUDHUNAGAR', 'state_id' => '30'],
['district_name' =>  'Ranipet', 'state_id' => '30'],
['district_name' =>  'KARAIKAL', 'state_id' => '26'],
['district_name' =>  'SHRAVASTI', 'state_id' => '34'],
['district_name' =>  'GANGANAGAR', 'state_id' => '28'],
['district_name' =>  'DEORIA', 'state_id' => '34'],
['district_name' =>  'JALAUN', 'state_id' => '34'],
['district_name' =>  'KHERI', 'state_id' => '34'],
['district_name' =>  'BUDAUN', 'state_id' => '34'],
['district_name' =>  'THENI', 'state_id' => '30'],
['district_name' =>  'SAMBHAL', 'state_id' => '34'],
['district_name' =>  'MADURAI', 'state_id' => '30'],
['district_name' =>  'MAYILADUTHURAI', 'state_id' => '30'],
['district_name' =>  'MAHOBA', 'state_id' => '34'],
['district_name' =>  'BULANDSHAHR', 'state_id' => '34'],
['district_name' =>  'SULTANPUR', 'state_id' => '34'],
['district_name' =>  'PERAMBALUR', 'state_id' => '30'],
['district_name' =>  'BIJNOR', 'state_id' => '34'],
['district_name' =>  'ALMORA', 'state_id' => '35'],
['district_name' =>  'UDAM SINGH NAGAR', 'state_id' => '35'],
['district_name' =>  'PAURI GARHWAL', 'state_id' => '35'],
['district_name' =>  'RAMPUR', 'state_id' => '34'],
['district_name' =>  'MURSHIDABAD', 'state_id' => '36'],
['district_name' =>  'KANPUR DEHAT', 'state_id' => '34'],
['district_name' =>  'NAINITAL', 'state_id' => '35'],
['district_name' =>  'RAE BARELI', 'state_id' => '34'],
['district_name' =>  'AURAIYA', 'state_id' => '34'],
['district_name' =>  'CHENNAI', 'state_id' => '30'],
['district_name' =>  'MAINPURI', 'state_id' => '34'],
['district_name' =>  'HARDOI', 'state_id' => '34'],
['district_name' =>  'CHAMPAWAT', 'state_id' => '35'],
['district_name' =>  'BANDA', 'state_id' => '34'],
['district_name' =>  'PURBA BARDHAMAN', 'state_id' => '36'],
['district_name' =>  'BANKURA', 'state_id' => '36'],
['district_name' =>  'BARABANKI', 'state_id' => '34'],
['district_name' =>  'Amethi', 'state_id' => '34'],
['district_name' =>  'BAGESHWAR', 'state_id' => '35'],
['district_name' =>  'UNNAO', 'state_id' => '34'],
['district_name' =>  'BIRBHUM', 'state_id' => '36'],
['district_name' =>  'CHITRAKOOT', 'state_id' => '34'],
['district_name' =>  'MALDAH', 'state_id' => '36'],
['district_name' =>  'COOCHBEHAR', 'state_id' => '36'],
['district_name' =>  'PITHORAGARH', 'state_id' => '35'],
['district_name' =>  'Alipurduar', 'state_id' => '36'],
['district_name' =>  '24 PARAGANAS SOUTH', 'state_id' => '36'],
['district_name' =>  'SHAMLI', 'state_id' => '34'],
['district_name' =>  'Jhargram', 'state_id' => '36'],
['district_name' =>  '24 PARAGANAS NORTH', 'state_id' => '36'],
['district_name' =>  'KUSHI NAGAR', 'state_id' => '34'],
['district_name' =>  'GONDA', 'state_id' => '34'],
['district_name' =>  'SITAPUR', 'state_id' => '34'],
['district_name' =>  'PASCHIM BARDHAMAN', 'state_id' => '36'],
['district_name' =>  'SOUTH DISTRICT', 'state_id' => '29'],
['district_name' =>  'HOWRAH', 'state_id' => '36'],
['district_name' =>  'TEHRI GARHWAL', 'state_id' => '35'],
['district_name' =>  'UTTAR KASHI', 'state_id' => '35'],
['district_name' =>  'NORTH DISTRICT', 'state_id' => '29'],
['district_name' =>  'WEST DISTRICT', 'state_id' => '29'],
['district_name' =>  'EAST DISTRICT', 'state_id' => '29'],
['district_name' =>  'DINAJPUR UTTAR', 'state_id' => '36'],
['district_name' =>  'DINAJPUR DAKSHIN', 'state_id' => '36'],
['district_name' =>  'HARIDWAR', 'state_id' => '35'],
['district_name' =>  'MUMBAI SUBURBAN', 'state_id' => '20'],
['district_name' =>  'HOOGHLY', 'state_id' => '36'],
['district_name' =>  'JALPAIGURI', 'state_id' => '36'],
['district_name' =>  'KOLKATA', 'state_id' => '36'],
['district_name' =>  'PURULIA', 'state_id' => '36'],
['district_name' =>  'South East','state_id' => '8'],
['district_name' =>  'KALIMPONG', 'state_id' => '36'],
['district_name' =>  'DARJEELING', 'state_id' => '36'],
['district_name' =>  'DEHRADUN', 'state_id' => '35'],
['district_name' =>  'NORTH AND MIDDLE ANDAMAN','state_id' => '1'],
['district_name' =>  'NICOBARS','state_id' => '1'],
['district_name' =>  'SOUTH ANDAMANS','state_id' => '1'],
['district_name' =>  'RUDRA PRAYAG', 'state_id' => '35'],
['district_name' =>  'BHADOHI', 'state_id' => '34'],
['district_name' =>  'CHAMOLI', 'state_id' => '35'],
['district_name' =>  'YANAM', 'state_id' => '26'],
        ];

        foreach ($districts as $key => $district) {
            District::create($district);
        }
    }
}
